const watchListActions = {
  ADD_WATCHLIST_MOVIE: "ADD_WATCHLIST_MOVIE",
  ADD_WATCHLIST_MOVIE_SUCCESS: "ADD_WATCHLIST_MOVIE_SUCCESS",
  ADD_WATCHLIST_MOVIE_FAILURE: "ADD_WATCHLIST_MOVIE_FAILURE",
  REMOVE_WATCHLIST_MOVIE: "REMOVE_WATCHLIST_MOVIE",
  REMOVE_WATCHLIST_MOVIE_SUCCESS: "REMOVE_WATCHLIST_MOVIE_SUCCESS",
  REMOVE_WATCHLIST_MOVIE_FAILURE: "REMOVE_WATCHLIST_MOVIE_FAILURE",
  GET_WATCHLIST_MOVIES: "GET_WATCHLIST_MOVIES",
  GET_WATCHLIST_MOVIES_SUCCESS: "GET_WATCHLIST_MOVIES_SUCCESS",
  GET_WATCHLIST_MOVIES_FAILURE: "GET_WATCHLIST_MOVIES_FAILURE",

  getWatchListMoviesRequest: () => {
    return {
      type: watchListActions.GET_WATCHLIST_MOVIES,
    };
  },
  addMovieRequest: () => {
    return {
      type: watchListActions.ADD_WATCHLIST_MOVIE,
    };
  },
  removeMovieRequest: () => {
    return {
      type: watchListActions.REMOVE_WATCHLIST_MOVIE,
    };
  },
};

export default watchListActions;
